### ISSUE TITLE
More about SQLi?

### ISSUE THREAD

**Issue by wlnirvana** [forax/write_your_own_java_framework_exercices#1]
This might be a dump question, but the ORM exercise readme mentions that:

> a library like SQLi creates one instance for each row of a query expressed in SQL. So two different queries on the same table may use two different classes

However, I am not able to find any relevant information about the library SQLi. Could you please give some pointers?

**Comment by forax** [comment]
brainfart :)
SQLi should be JDBi (https://jdbi.org/)

**Comment by forax** [comment]
fixed by https://github.com/forax/write_your_own_java_framework_exercices/commit/642185237fa941b1593e28b33171a61dce178dc0
